### ISSUE TITLE
盒盖才能启动

### ISSUE THREAD

**Issue by Yuanlailai** [plumxl/hasee-z7-kp7gt-macos10.13.6#2]
开机到一半就会黑屏，然后心里默念等他开机完盒盖再翻盖，才会唤醒进入密码输入界面，原谅绿好像不会，我的是红的

**Comment by plumxl** [comment]
我也不会调，问题很多，基本能用

**Comment by plumxl** [comment]
我也不会调，问题很多，基本能用

**Comment by plumxl** [comment]
> 开机到一半就会黑屏，然后心里默念等他开机完盒盖再翻盖，才会唤醒进入密码输入界面，原谅绿好像不会，我的是红的

我也不会调，问题很多，基本能用
